version: 2
updates:

  # Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "*"
        versions: ["<next-major"] # ignore minor/patch, alert only on majors

  # GitHub Actions used in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
